language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - PHPUNIT=7.*
  - PHPUNIT=8.*
  - PHPUNIT=dev-master MIN_STABILITY=dev

matrix:
  allow_failures:
    - env: PHPUNIT=dev-master MIN_STABILITY=dev

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - if [ "$MIN_STABILITY" != "" ]; then composer config minimum-stability $MIN_STABILITY; fi
  - composer require phpunit/phpunit:${PHPUNIT}

script:
  - ./vendor/bin/phpunit
